// ping.cpp – publishes an incrementing integer to the "PingPongTopic" topic.

#include <chrono>
#include <cstdint>
#include <cstring>
#include <iostream>
#include <thread>

#include "dds/dds.h"
#include "ping_pong.h"   // generated by idlc from ping_pong.idl

int main()
{
    // ── Participant ──────────────────────────────────────────────────────────
    dds_entity_t dp = dds_create_participant(DDS_DOMAIN_DEFAULT, nullptr, nullptr);
    if (dp < 0) {
        std::cerr << "[ping] dds_create_participant: " << dds_strretcode(-dp) << '\n';
        return 1;
    }

    // ── Topic ────────────────────────────────────────────────────────────────
    dds_entity_t topic = dds_create_topic(
        dp, &PingPong_Msg_desc, "PingPongTopic", nullptr, nullptr);
    if (topic < 0) {
        std::cerr << "[ping] dds_create_topic: " << dds_strretcode(-topic) << '\n';
        return 1;
    }

    // ── Writer with reliable QoS ─────────────────────────────────────────────
    dds_qos_t *qos = dds_create_qos();
    dds_qset_reliability(qos, DDS_RELIABILITY_RELIABLE, DDS_SECS(10));

    dds_entity_t writer = dds_create_writer(dp, topic, qos, nullptr);
    dds_delete_qos(qos);
    if (writer < 0) {
        std::cerr << "[ping] dds_create_writer: " << dds_strretcode(-writer) << '\n';
        return 1;
    }

    // ── Wait for at least one matching subscriber ────────────────────────────
    std::cout << "[ping] Waiting for a subscriber...\n" << std::flush;
    dds_publication_matched_status_t pm{};
    do {
        std::this_thread::sleep_for(std::chrono::milliseconds(200));
        dds_get_publication_matched_status(writer, &pm);
    } while (pm.current_count == 0);

    std::cout << "[ping] Subscriber matched – starting to publish.\n\n" << std::flush;

    // ── Publish loop ─────────────────────────────────────────────────────────
    for (int32_t i = 0; ; ++i) {
        PingPong_Msg msg{};
        msg.value = i;

        dds_return_t rc = dds_write(writer, &msg);
        if (rc != DDS_RETCODE_OK) {
            std::cerr << "[ping] dds_write error: " << dds_strretcode(-rc) << '\n';
        } else {
            std::cout << "[ping] Sent: " << i << '\n' << std::flush;
        }

        std::this_thread::sleep_for(std::chrono::seconds(1));
    }

    dds_delete(dp);
    return 0;
}
